### ISSUE TITLE
file_stats.sh chokes on directories with spaces in the name

### ISSUE THREAD

**Issue by benjaminjackson** [gilesbowkett/rewind#5]
Sample error:

    fatal: ambiguous argument 'Sources/LFSignupDataSource.h': unknown revision or path not in the working tree

That path is actually `Data Sources/LFSignupDataSource.h`. Probably just needs to escape spaces in the name when passing files off to git.

**Comment by gilesbowkett** [comment]
thanks, resolved. my bad re the long delay.
