### ISSUE TITLE
Collect stats if a commit author matches some criteria

### ISSUE THREAD

**Issue by StephenHynes7** [gilesbowkett/rewind#6]
I think the base idea here is pretty awesome, however it collects stats on files I really couldn't care less about and that is mainly library files and other such files that are never touched by developers. 

It would be nice if we could specify a regex that when we check each file if the latest commit author matches our regex then we collect stats on it, otherwise we move on. This also means we can report on Libs that developers have modified.

**Comment by gilesbowkett** [comment]
that'd be worth doing. PR welcome.
