### ISSUE TITLE
Tally authors oneliner

### ISSUE THREAD

**Issue by barrkel-m20** [gilesbowkett/rewind#9]
find -iname '*.js' | xargs -n 1 git log | grep Author | egrep -o 'Author:.*' | sed 's|Author: ||' | sort | uniq -c | sort -n

No need for separate Ruby, or while loops etc.

HTH

**Comment by gilesbowkett** [comment]
thanks for this, sorry for slow response.

so I had to change it a little to run in bash on OS X:

`find . -name '*.coffee' |
xargs -n 1 git log |
grep Author |
egrep -o 'Author:.*' |
sed 's|Author: ||' |
sort |
uniq -c |
sort -n`

and then I got results which indicated only a total of 48 commits for a repo which GitHub says has 576 commits.

having `tally_authors` be in bash is definitely preferable to Ruby — this repo should be very portable and low-overhead. but I'm going to close this Issue in favor of https://github.com/gilesbowkett/rewind/pull/12.
